---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
# automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token
---
apiVersion:
kind: pod
metadata:
  name: sa-pod
spec:
  serviceAccountName: build-robot
  automountServiceAccountToken: false
  containers:
    - name: task-sa-container
      image: busybox
